### PR TITLE
Add syntax highlighting which is compatible with Nano versions 2.5.x or older.

### PR DESCRIPTION
**Pull request by thomas-w-holleis**
This is a modified version from http://git.savannah.gnu.org/cgit/nano.git/plain/doc/syntax/rust.nanorc?id=1349c1d02c866eb478e2549a5cfc1b61a57b1583

### CODE REVIEW

**Comment by thomas-w-holleis** [comment]
Since 28.06.2016 the nano-config repository will no longer be maintained because the syntax highlighting file 'rust.nanorc' was moved to the official GNU nano project (https://savannah.gnu.org/projects/nano).

The problem with the current released file is that it will raise an error message during nano startup when using a nano version prior 2.6.0. The user can confirm the error message and nano with syntax highlighting should continue to work but this can be annoying.

A solution would be to add the file also to older nano versions e.g. 2.4.x but older versions are set in stone and will no longer be updated. See https://savannah.gnu.org/bugs/?48555

It would be very convenient for all developers which uses nano 2.5.x or older if someone provide an suitable Rust syntax highlighting file 'rust.nanorc' (again) because currently a lot of developers use older nano editors. Probably this situation will not change the next few years e.g. especially for users with LTS distros.

**Comment by brson** [comment]
Thanks for the PR.

Ugh, that's a pain. Is it possible to maintain a single rust.nanorc that is compatible with all versions of nano, and can it be maintained upstream?

If we did maintain this one here for older nano's it makes the situation quite confusing for prospective devs. I guess we'd want the README to be very explicit about the purpose of this repository.

**Comment by brson** [comment]
cc @rust-lang/tools We recently upstreamed our nano config, and now the upstream nano config as no longer compatible with older revisions of nano. So this is proposing that we again maintain a nano config, just for old nanos.

**Comment by alexcrichton** [comment]
Agreed it'd be best if we could upstream fixes so it could just be maintained in one place, but otherwise this seems fine to me so long as we're super clear in the README

**Comment by thomas-w-holleis** [comment]
Thanks for answering.
The 'rust.nanorc' from this PR is brand new and already compatible with nano releases 2.5 or older, so what are the next steps?
Who maintain/update the README file? Can I help with some things?

**Comment by brson** [comment]
@thomas-w-holleis Is this config compatible with 2.6 as well? In other words, is this config better in all cases than the one upstream?

If you update the README to indicate that 1) nano 2.6.1 and later come with Rust support, 2) this repo contains a nano configuration compatible with older releases of nano, then I'll merge this.

Thanks.

**Comment by thomas-w-holleis** [comment]
@brson Yes, this file is compatible with 2.6. I have done some tests and it looks ok. The syntax highlighting output for this file and the one upstream should be the same.

I will do the update of the README (probably on Sunday).

**Comment by thomas-w-holleis** [comment]
@brson I update the README and also re-add the license files.

**Comment by brson** [comment]
Thanks @thomas-w-holleis !

**Pull request merged**
