### PR TITLE
Announced that `rust.nanorc` has been contributed upstream

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Do you know the protocol for contributing changes to upstream as well? It'd be cool if we could also leave notes for contributing upstream as well (if anyone runs across this)

**Comment by djc** [comment]
@alexcrichton I updated and extended the new README a bit, please review again.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by brson** [comment]
Thanks @djc!

**Pull request merged**
